### ISSUE TITLE
Add Windows as a supported platform in our automated test environment (epic)

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1134]
### Problem
Currently, our automated test environment only supports the Ubuntu operating system. This limits our ability to catch issues on the windows platform in our test environment. 

### Solution
Include Windows as a supported platform in our automated test environment. By including windows we ensure that we catch issues for the windows platform as early as possible.

### Other alternatives
One alternative solution is to rely on manual testing on Windows machines. However, this approach is time-consuming, error-prone, and lacks the efficiency and scalability of automated testing. By including Windows as a supported platform in our automated test environment, we can leverage the benefits of automation and streamline our testing process across multiple operating systems.

## Todo:
Convert the following GitHub actions into supporting a platform agnostic test environment.
- [x] https://github.com/serverpod/serverpod/issues/1205
- [ ] https://github.com/serverpod/serverpod/issues/1206
- [x] https://github.com/serverpod/serverpod/issues/1207
- [x] https://github.com/serverpod/serverpod/issues/1208

**Comment by SandPod** [comment]
Closing this as this is simply pointing to a single separate issue: https://github.com/serverpod/serverpod/issues/1206
