### ISSUE TITLE
Streamline import references for generated files.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2967]
**Is your feature request related to a problem? Please describe.**
In an effort to support placing endpoint and model files anywhere in the project, tracked here: https://github.com/serverpod/serverpod/issues/964, a streamlined generation order is required when generating model files, `protocol.dart` and `client.dart`/ `endpoints.dart`

Current dependency graph:

<img src="https://github.com/user-attachments/assets/35d2c0f4-dd85-4d49-aef4-89fce4db5ddb" width="500">

**Describe the solution you'd like**
Wanted dependency graph:

<img src="https://github.com/user-attachments/assets/248a63a7-4110-45a7-a657-b86a57e021c0" width="500">

**TODO**

1. [x] Remove self dependency in `protocol.dart`
2. [ ] Remove exporting `client.dart` in `protocol.dart` on client side generation.
3. [x] Depend directly on models from models.
4. [ ] Depend on `protocol.dart` instead of models in `client.dart` and `endpoints.dart`.

**Comment by SandPod** [comment]
Removing the export of client in `protocol.dart` would require all our users to update their code in the generated client project and is therefore a breaking change. It is also not required to implement the rest of the changes to allow different project structures.

There is no way to solely depend on `protocol.dart` in `client.dart` and `endpoints.dart` since the import there is user defined.

Will skip the last two remaining tasks and close this issue as complete.
