### ISSUE TITLE
The method 'copyWith' isn't defined for Custom Class and ProtocolSerialization issues

### ISSUE THREAD

**Issue by Dario-Ciceri** [serverpod/serverpod#2977]
Hi, as per title I have some problems that are easily solved but I would like them to be mentioned in the documentation or handled directly by serverpod.

The documentation states:

> If you need certain fields to be omitted when transmitting to the client-side, your server-side custom class should implement the ProtocolSerialization interface. This requires adding a method named toJsonForProtocol(). Serverpod will then use this method to serialize your object for protocol communication. If the class does not implement ProtocolSerialization, Serverpod defaults to using the toJson() method.

I don't need to use `ProtocolSerialization` yet, but without the `toJsonForProtocol` method, the automatically generated code creates problems, saying that it doesn't find `toJsonForProtocol` instead of using `toJson` directly. Also, the `copyWith` method is also not automatically generated and I did not read anywhere in the documentation that it has to be created and I thought it was automatically generated. Finally, it should be mentioned in the documentation that you need to install the `serverpod_serialization` dependency in order to use `ProtocolSerialization` in the custom class, something that is perhaps rather obvious but would still be good to remember.

I am currently using my custom class as the elements type (`RBACPermission`) of a list in a class generated with .spy.yaml, if that helps.

```
class: UserRole
table: user_role
fields:
  name: String
  users: List<User>?, relation(optional, name=users_role) #! bidirectional relation
  scopes: List<RBACPermission>
```

Thanks 😄.

**Serverpod versions**
 -  _CLI Version: Serverpod version: 2.1.5
 - _Library version: 2.1.5

**Platform information**
Docker and Docker compose, Windows.

**Comment by SandPod** [comment]
> saying that it doesn't find toJsonForProtocol instead of using toJson directly.

This is a bug; there should be no need to implement the `toJsonForProtocol` method.

> install the serverpod_serialization dependency in order to use ProtocolSerialization in the custom class,

Yes, we should update the documentation to clarify this.

> Also, the copyWith method is also not automatically generated

This needs to be added to the documentation. We do not modify the custom classes. So, in order for the `copyWith` method to work, this needs to be implemented in the custom class as well.

These are implemented as `deep copies` in Serverpod and it is recommended to do this for custom classes as well.

### Tasks
- [ ] Remove requirement for `toJsonForProtocol` for custom classes.
- [ ] Document the dependency towards `serverpod_serialization` in order to implement `ProtocolSerialization`.
- [ ] Document the requirement to implement `copyWith` method for custom classes.
